microsoft/sca-fuzzer

- README.md
- src/tests/test-detection.yaml
- src/tests/test-nondetection.yaml
- the README command `cd` into a directory which does not exist
- Configuration files in `src/tests` directory specify  instructions' category that does not match the categories' names.
> Fix README and configuration files

- src/factory.py
- src/x86/x86_model.py
This PR addresses the following issues:
- "ooo-gp" and "noncanonical" refer to the same contract.
- Rename `X86NonCanonicalOOO` to `X86NonCanonicalAddress` since it does not inherit from 'OOO' contract anymore.
- `X86NonCanonicalAddress` is not functional
Changes:
- remove "ooo-gp"
- Fix `X86NonCanonicalAddress`
> Exception handling

- src/model.py
- src/x86/executor/main.h
- src/x86/isa_spec/get_spec.py
- src/x86/tests/acceptance/acceptance.bats
- src/x86/tests/unit_model.py
- src/x86/x86_config.py
- src/x86/x86_fuzzer.py
- src/x86/x86_generator.py
This PR includes:
* adds support for #BP and #DB
* when testing instruction-triggered faults, check for presence of the corresponding instructions in the instruction set
* refactoring: UnicornModel.handled_faults is now a set instead of a list
* fixed failing tests
> Software Interrupts + fixed tests

- src/x86/x86_model.py
This contract isn't actually satisfied - I still see violations. But this version is at least somewhat closer to the previous one, so we might as well have it for future reference.
> x86/model: refined Div-by-zero contract

- src/config.py
- src/generator.py
This PR implements two new config fields that give the user better control over the program generator's branch placement. (This seeks to resolve issue #37). Here's a description of what these new fields do:
The program generator uses an internal list of control-flow instruction specifications to generate random branch instructions at the end of basic blocks. This internal list contains both conditional *and* unconditional branches. So, when a random control-flow instruction is generated, it's possible either type will be produced.
The `conditional_branch_selection_attempts` config field helps control this. This PR adds a loop to the program generator that is controlled by this field. When generating a random control-flow instruction, this loop will:
* (If the field is set to a positive …
> generator: ensure generation of conditional branches

- src/x86/x86_model.py
AMD CPUs (and I'm guessing Intel CPUs too) optimize dependency tracking for certain instructions where it's possible to ensure that a value is never dependent. This patch refines the OOO contract to include those cases.
> x86/model: refined dependency tracking in OOO contract

- src/interfaces.py
- src/x86/x86_generator.py
- src/x86/x86_model.py
This PR contains several fixes to the noncanonical contract.
1. In the generator I create a deepcopy of the operands when inserting instrumentation. Otherwise further instrumentation that modifies the instrumented instruction's operand also modifies the instrumentation instructions ' operands.
2.  In the noncanonical contract, during handling of the GP exception, we overwrite the register that contains the address. We need to restore its content afterward. 
3. In the noncanonical address pass  we prevent registers reuse. This makes the contract implementation logic simpler. We  avoid cases where the destination is partially overwritten and should be properly restored after the exception.
> Fix GP noncanonical contract

- src/config.py
- src/generator.py
- src/interfaces.py
Updates to Input.get_registers() to avoid slicing off the final 8 register bytes.
Add config option `input_entropy_for_imm` to constrain arithmetic immediate values to be constrained to the same number of values that can be held in the input registers based on entropy setting.
Add full randomization to ARM bitmask immediates. This is currently in the RandomGenerator class but could be moved to Arch specific generators if needed. Currently it asserts only arm64 should be using bitmask immediates.
> Updates to Immediate Generation and Input Generation

- src/config.py
- src/fuzzer.py
- src/input_generator.py
- src/interfaces.py
- src/util.py
- src/x86/x86_executor.py
- src/x86/x86_fuzzer.py
The PR introduces several changes to the overall fuzzing process:
- Introduces a config option `model_min_nesting` to optimize the throughput of experiments that experience a lot of benign nested mispredictions (bada76a) 
- Adds a fast-path hardware tracing option that collects htraces first without filtering and, if a violation is detected, enabled noise filtering and re-collectrs htraces (34ccc5874cd78ae35ecac38f7b2ff34eaf4524d1)
- Separates the input generator state into main state (updated when generating the original batch of inputs) and boosting state (updated when boosting inputs). The later is reset when the fuzzer re-boosts the same batch of inputs, to ensure consistent results (c7a852d12267cbb26e338acc0162bbb206deb181)
- (minor) Refactors statistics on false positives …
> fuzzer: fast-path executor and other optimizations

- src/util.py
- src/x86/executor/main.c
- src/x86/executor/main.h
- src/x86/executor/measurement.c
- src/x86/executor/templates.c
- src/x86/x86_executor.py
- src/x86/x86_fuzzer.py
The PR introduces a new measurement mode that cuts a few corners in the measurement process to achieve considerably higher performance (as high as 10x faster on my benchmarks).
Namely, this mode:
* doesn't reset uarch state
* executes the Prime stage of P+P only once
* doesn't initialize overflow pages
These changes can lead to corrupted hardware traces. Accordingly, the mode is exclusively used by the filters (speculation and observation filters). It is not meant to be used for collecting hardware traces.
> x86/executor: add quick-and-dirty measurement for faster pre-filtering

- src/config.py
- src/factory.py
- src/x86/x86_config.py
- src/x86/x86_executor.py
The executor default to the intel one. 
An option to select the executor already exist but it is not used.
This PR adds two options for the executor: 'x86-64-intel' and 'x86-64-amd'.
> factory: add AMD executor

- src/x86/executor/include/shortcuts.h
Hi! Surprisingly for my context (Linux 6.2, Ubuntu 22.04) it does not compile without this include, so I propose adding it. Thanks!
> Add include in shortcuts.h

- revizor.py
Hi!
I stumbled into a quite misleading situation. When I do not have `elftools` installed, the error message returned by Revizor is:
```
Traceback (most recent call last):
File "/home/user/gits/olek-sca-fuzzer/revizor.py", line 12, in <module>
from revizor.cli import main
File "/home/user/gits/olek-sca-fuzzer/revizor.py", line 12, in <module>
from revizor.cli import main
ModuleNotFoundError: No module named 'revizor.cli'; 'revizor' is not a package
```
Which is not descriptive of the underlying problem.
The proposed fix will give such an error message:
```
Unable to import main from src.cli.
Issue during import of src.cli: `No module named 'elftools'`
```
Feel free to edit the error message.
Thanks!
> Clarify import error message

- src/x86/executor/code_loader.c
- src/x86/executor/hw_features/fault_handler.c
- src/x86/executor/measurement.c
Hi there!
This removes the warnings from objtool:
```
/path/to/repo/src/x86/executor/x86_executor.o: warning: objtool: nmi_handler_wrapper+0x5f: missing int3 after ret
/path/to/repo/src/x86/executor/x86_executor.o: warning: objtool: fallback_handler_wrapper+0xcb9: missing int3 after ret
/path/to/repo/src/x86/executor/x86_executor.o: warning: objtool: bubble_handler_wrapper+0xcc7: missing int3 after ret
/path/to/repo/src/x86/executor/x86_executor.o: warning: objtool: main_segment_template+0x305: missing int3 after ret
/path/to/repo/src/x86/executor/x86_executor.o: warning: objtool: main_segment_template_dbg_gpr+0x2c9: missing int3 after ret
/path/to/repo/src/x86/executor/x86_executor.o: warning: objtool: unsafe_bubble_wrapper+0x66: missing int3 after ret
```
We must also clarify the …
> x86/executor: add int3 after ret to please objtool

- src/asm_parser.py
- src/cli.py
- src/fuzzer.py
- src/generator.py
- src/interfaces.py
- src/x86/x86_asm_parser.py
- src/x86/x86_elf_parser.py
- src/x86/x86_executor.py
- src/x86/x86_fuzzer.py
- src/x86/x86_generator.py
- src/x86/x86_target_desc.py
The PR introduces a new fuzzing mode (`tfuzz`) that expands randomization macros and creates new test cases based on a template.
Usage:
```
./revizor.py tfuzz -s base.json -c conf.yaml -t template.asm -i 10 -n 10
```
Contents of the template:
```
.intel_syntax noprefix
.test_case_enter:
.section .data.main
.function_start:
.macro.random_instructions.64.32:
.test_case_exit:
```
> generator: add template-based fuzzing mode

- src/config.py
Hi!
Makes it easier when moving between AMD and Intel.
You may want to edit `default` for intel like in the current 1.3-dev.
Please edit in place as you like.
> config: automatic selection of vendor-specific executor

- src/arm64/arm64_model.py
- src/arm64/tests/unit_model.py
- src/factory.py
This PR implements the "cond" execution model for the ARM64 architecture.
I've based it closely on the x86_64 implementation and it seems to prevent violations in my tests with the gem5 CPU simulator but perhaps someone with actual ARM hardware should try it out...
> arm64: add COND model

- src/factory.py
- src/model.py
The default constant-time tracer tracks full addresses. This PR adds a new tracer that tracks addresses at cache line granularity.
> model: added tracer to track cache line granularity accesses

- src/config.py
Makes #85 work. Else the automatically found executor will always be overwritten with an empty string.
Thanks!
Flavien
> config: [fix] get automatic executor vendor

- src/cli.py
Hi!
I found it quite confusing that the `-i` of `minimize` does not correspond to the `-i` of `tfuzz` but to its `-n`.
This PR might imply some changes in the docs or some higher-level scripts, potentially.
Thanks!
Flavien
> Update cli.py to harmonize flags of tfuzz and minimize

- .gitignore
- docs/cli.md
- src/cli.py
Will crash on tfuzz run otherwise.
Adding the 2 entries to gitignore will allow easy git changes whilst runs are active.
Side note: Using "CTRL+C" to cancel the run halfway will now cause it to spit out a "bug" violation for the canceled run (assuming this is to detect archfuzz bugs). Be careful to distinguish between actual architectural bugs and the false positives that are just testing artifacts.
> cli: [fix] Invalid argument in CLI tfuzz mode

- .github/workflows/python-lint-and-test.yaml
With the new release, we adopted a new branch convention. This PR updates the corresponding list of branches in github CI
> root: [build] update list of tested branches in CI

- docs/quick-start.md
- rvzr/model_dynamorio/Makefile
- rvzr/model_dynamorio/adapter/.clang-tidy
- rvzr/model_dynamorio/backend/.clang-tidy
- rvzr/model_dynamorio/backend/cli.cpp
- rvzr/model_dynamorio/backend/include/observables.hpp
- rvzr/model_dynamorio/backend/include/speculator_abc.hpp
- rvzr/model_dynamorio/backend/include/speculators/cond.hpp
- rvzr/model_dynamorio/backend/include/tracer_abc.hpp
- rvzr/model_dynamorio/backend/include/util.hpp
- rvzr/model_dynamorio/backend/tracer_abc.cpp
- rvzr/model_dynamorio/backend/tracers/ct.cpp
- rvzr/model_dynamorio/backend/tracers/pc.cpp
- rvzr/model_dynamorio/model.py
- tests/runtests.sh
This PR contains a couple minor improvements related to the current dynamorio model:
- `cmake` version >= 3.20 doesn't support `--config=Debug` anymore -- ported to new `cmake`
- added `make clean` to dynamorio Makefile
- fixed an outdated dynamorio flag in the quickstart doc
- clang-tidy now scans `.h`/`.hpp` files as well - the reported errors have been either fixed or added to the ignore-list
> Apply clang-tidy to Dynamorio model headers

- rvzr/model_dynamorio/backend/dispatcher.cpp
- rvzr/model_dynamorio/backend/factory.cpp
- rvzr/model_dynamorio/backend/include/tracer_abc.hpp
- rvzr/model_dynamorio/backend/include/tracers/ct.hpp
- rvzr/model_dynamorio/backend/include/tracers/ind.hpp
- rvzr/model_dynamorio/backend/include/tracers/pc.hpp
- rvzr/model_dynamorio/backend/include/types/trace.hpp
- rvzr/model_dynamorio/backend/tracer_abc.cpp
- rvzr/model_dynamorio/backend/tracers/ct.cpp
- rvzr/model_dynamorio/backend/tracers/ind.cpp
- rvzr/model_dynamorio/backend/tracers/pc.cpp
- rvzr/model_dynamorio/model.py
- rvzr/model_dynamorio/trace_decoder.py
- rvzr/traces.py
- tests/x86_tests/min_x86.json
- tests/x86_tests/unit_model_dr.py
Add a tracer that logs the target of indirect calls/indirect jumps and rets.
This requires the following modifications:
- modify `observer_instruction()` for all tracers to also receive the DR context (needed by `ind` for instruction decoding)
- add the tracer to `factory.cpp`
- add relevant changes for decoding the `ind` trace entry (in `trace_decoder.py` and `model.py`)
- add unit test and make relevant changes to the parser
> Add IND tracer for indirect calls, indirect branches and returns

- rvzr/model_dynamorio/backend/cli.cpp
- rvzr/model_dynamorio/backend/dispatcher.cpp
- rvzr/model_dynamorio/backend/factory.cpp
- rvzr/model_dynamorio/backend/include/cli.hpp
- rvzr/model_dynamorio/backend/include/factory.hpp
- rvzr/model_dynamorio/backend/include/speculator_abc.hpp
- rvzr/model_dynamorio/backend/speculator_abc.cpp
- rvzr/model_dynamorio/model.py
- tests/x86_tests/unit_model_dr.py
Add the `--poison-value` flag to the DR client. If a value is specified though this flag, such value will be forwarded to the destination register of faulty loads during speculation, instead of just rolling back the speculation.
This is useful in cases where the faulty load's address is attacker-controlled to evaluate the presence of leak gadgets (e.g. double loads or dispatch gadgets.
> model/dr: [feat] poison faulty loads
